# Generated by Django 2.0 on 2020-03-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_authorised',
            field=models.BooleanField(default=False, verbose_name='Авторизован ли пользователь'),
        ),
    ]
